version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "[FIX] "
    groups:
      dependencies:
        patterns:
          - "*"
    reviewers:
      - "dixgrake"
    labels: [ ]
